// vocab-data.js — 英语词汇数据
// 新增日期只需在下方数组追加一个对象，然后刷新 HTML 即可
// 格式：{ date: "显示日期", words: [ {en, phonetic, pos, meaning, example, root, ...}, ... ] }
// 含义以牛津学习词典(Oxford Advanced Learner's Dictionary)美式释义为准

const VOCAB_DATA = [
  {
    date: "📅 2026-05-17（47词）",
    words: [
      { en:"pronunciation", phonetic:"/prəˌnʌnsiˈeɪʃn/", pos:"n.", meaning:"❶ 发音方式（某个词或语言的读法） ❷ 某人的发音（口音）", example:"Your pronunciation of 'th' needs work.", root:"pro(向前)+nounce(说)+ation → 把话说出来的方式 → 发音" },
      { en:"comprehension", phonetic:"/ˌkɑːmprɪˈhenʃn/", pos:"n.", meaning:"❶ 理解力（读懂/听懂的能力） ❷ 理解练习（如阅读理解、听力理解）", example:"The test has a listening comprehension section.", root:"com(完全)+prehend(抓住) → 完全抓住意思 → 理解" },
      { en:"sentence structure", phonetic:"/ˈsentəns ˈstrʌktʃər/", pos:"n.", meaning:"句子结构（主谓宾等成分的排列方式）", example:"Vary sentence structure for better writing.", root:"sentence(句子)的structure(建造方式) → 句子怎么搭的", noAudio:true },
      { en:"method", phonetic:"/ˈmeθəd/", pos:"n.", meaning:"❶ 方法、办法（做某事的特定/系统方式） ❷ 条理、秩序（做事有计划、有组织的品质）", example:"The method we used was surveys.", root:"meta(跟随)+hodos(道路) → 沿着走的路 → 方法" },
      { en:"comprehensible input", phonetic:"/ˌkɑːmprɪˈhensəbl ˈɪnpʊt/", pos:"n.", meaning:"可理解性输入（Krashen二语习得理论：略高于当前水平的输入，i+1）", example:"Comprehensible input is key in Krashen's theory.", root:"能被理解(comprehend)的输入(input) → 听得懂的材料", noAudio:true },
      { en:"lesson", phonetic:"/ˈlesn/", pos:"n.", meaning:"❶ 一节课 ❷ 教训（从经历中学到的道理） ❸ 课文", example:"That failure taught me a valuable lesson.", root:"learn的变体 → 学到的东西 → 一课/教训" },
      { en:"adventure", phonetic:"/ədˈventʃər/", pos:"n.", meaning:"❶ 冒险（不寻常的、刺激的经历） ❷ 冒险精神", example:"We had many adventures in South America.", root:"ad(向)+vent(来) → 向未知的未来走去 → 冒险" },
      { en:"goal", phonetic:"/ɡoʊl/", pos:"n.", meaning:"❶ 目标、目的 ❷ 球门 ❸ 进球", example:"My goal is to become fluent.", root:"古义: 障碍/边界 → 需要到达的终点 → 目标" },
      { en:"quiz", phonetic:"/kwɪz/", pos:"n./v.", meaning:"❶ n. 小测验、问答比赛 ❷ v. 盘问、考问", example:"We have a quiz on chapter 3.", root:"起源不确定，可能来自拉丁语qui es? → 问你知道多少 → 小测验" },
      { en:"chance", phonetic:"/tʃæns/", pos:"n./v.", meaning:"❶ n. 可能性（某事发生的概率，a chance of） ❷ n. 机会（做某事的合适时机，a chance to do） ❸ n. 风险、冒险（take a chance） ❹ n. 偶然、运气（by chance, pure chance） ❺ v. 冒险做（chance doing/on） ❻ v. 碰巧发生（it chanced that…）", example:"This is your chance to prove yourself.", root:"cadere(落下) → 像骰子落下一样 → 随机的可能性" },
      { en:"software", phonetic:"/ˈsɔːftwer/", pos:"n.", meaning:"软件（计算机程序和指令的统称，不可数）", example:"Install the software first.", root:"soft(软的)+ware(商品) → 看不见摸不着但能用的程序 → 软件" },
      { en:"confusion", phonetic:"/kənˈfjuːʒn/", pos:"n.", meaning:"❶ 困惑、糊涂 ❷ 混乱、混淆 ❸ 混同（把A当成B）", example:"There was confusion about the time.", root:"con(一起)+fundere(倾倒) → 全混在一起分不清 → 困惑/混乱" },
      { en:"term", phonetic:"/tɜːrm/", pos:"n./v.", meaning:"❶ n. 术语、措辞 ❷ n. 学期 ❸ n. 条款、条件 ❹ n. 期限、任期 ❺ v. 把…称为", example:"What does this term mean?", root:"terminus(边界/终点) → 划定范围的词 → 术语/期限" },
      { en:"visual", phonetic:"/ˈvɪʒuəl/", pos:"adj./n.", meaning:"❶ adj. 视觉的、看得见的 ❷ n. 视觉资料（图片、图表等）", example:"The visuals drove the point home.", root:"vis(看) → 与看见有关的 → 视觉的" },
      { en:"routine", phonetic:"/ruːˈtiːn/", pos:"n./adj.", meaning:"❶ n. 常规、例行公事 ❷ n. 一套动作（舞蹈/喜剧等） ❸ adj. 日常的、普通的", example:"Reading is my daily routine.", root:"route(路线) → 每天走同一条路 → 常规" },
      { en:"stick", phonetic:"/stɪk/", pos:"n./v.", meaning:"❶ n. 棍、棒、枝条 ❷ v. 粘贴、贴上 ❸ v. 坚持、坚守 ❹ v. 卡住、插着", example:"Stick to the plan.", root:"古义: 树枝/棍子 → 用棍子固定住 → 粘住/坚持" },
      { en:"part", phonetic:"/pɑːrt/", pos:"n./v.", meaning:"❶ n. 部分、组件 ❷ n. 角色（戏剧中的） ❸ n. 地区、区域 ❹ v. 分开、散开", example:"She is a part of our team.", root:"pars(部分) → 整体中的一块 → 部分" },
      { en:"prompt", phonetic:"/prɑːmpt/", pos:"adj./n./v.", meaning:"❶ adj. 迅速的、及时的 ❷ v. 提示、促使 ❸ n. 提示词、提示符", example:"Write a better prompt for better results.", root:"pro(向前)+emere(拿) → 把想法拿出来的 → 提示/促使" },
      { en:"tense", phonetic:"/tens/", pos:"n./adj.", meaning:"❶ n. 时态（动词的时间形式） ❷ adj. 紧张的、绷紧的", example:"English has 12 tenses.", root:"tempus(时间) → 动词标记时间的形状 → 时态；拉紧 → 紧张" },
      { en:"design", phonetic:"/dɪˈzaɪn/", pos:"v./n.", meaning:"❶ v. 设计、构思 ❷ n. 设计方案 ❸ n. 图案、花纹 ❹ n. 意图、企图", example:"The app is designed to help beginners.", root:"de(出)+signare(标记) → 做出标记来规划 → 设计" },
      { en:"reach", phonetic:"/riːtʃ/", pos:"v./n.", meaning:"❶ v. 到达、抵达 ❷ v. 伸手够到 ❸ v. 达成（协议等） ❹ n. 伸手范围 ❺ n. 影响范围", example:"We reached the summit at dawn.", root:"古义: 伸展手臂 → 伸手够到的范围 → 到达" },
      { en:"study", phonetic:"/ˈstʌdi/", pos:"v./n.", meaning:"❶ v. 学习、研究 ❷ v. 端详、细看 ❸ n. 学习 ❹ n. 研究、调查 ❺ n. 书房", example:"She studies English every day.", root:"studium(热心) → 投入热情去做 → 学习/研究" },
      { en:"practice", phonetic:"/ˈpræktɪs/", pos:"v./n.", meaning:"❶ v./n. 练习、训练 ❷ n. 惯例、做法 ❸ n. 业务、执业（医生/律师等）", example:"Practice makes perfect.", root:"practicus(实用的) → 反复做直到熟练 → 练习" },
      { en:"stick around", phonetic:"/stɪk əˈraʊnd/", pos:"phrasal v.", meaning:"留在原地、待着不走（口语）", example:"Stick around until you reach your goals.", root:"stick(粘住)+around(在周围) → 粘在附近不走 → 待着", noAudio:true },
      { en:"allow", phonetic:"/əˈlaʊ/", pos:"v.", meaning:"❶ 允许、准许（allow sb to do） ❷ 使能够、给…机会（allow access） ❸ 留出、给予（时间/空间，allow time for） ❹ 接受、承认（allow that…）", example:"Smoking is not allowed here.", root:"ad(向)+laudare(赞美) → 给予认可 → 允许" },
      { en:"reinforce", phonetic:"/ˌriːɪnˈfɔːrs/", pos:"v.", meaning:"❶ 加强、强化（观点/行为等） ❷ 增援（军事） ❸ 加固（建筑/结构）", example:"This data reinforces our conclusion.", root:"re(再)+in+force(力量) → 再次注入力量 → 加强" },
      { en:"explain", phonetic:"/ɪkˈspleɪn/", pos:"v.", meaning:"❶ 解释、说明 ❷ 为…辩解、说明原因", example:"Let me explain it to you.", root:"ex(出)+plain(平坦) → 把复杂的摊平说清楚 → 解释" },
      { en:"ensure", phonetic:"/ɪnˈʃʊr/", pos:"v.", meaning:"确保、保证（某事一定发生）", example:"Ensure that all doors are locked.", root:"en(使)+sure(确定) → 使之确定 → 确保" },
      { en:"solidify", phonetic:"/səˈlɪdɪfaɪ/", pos:"v.", meaning:"❶ 使凝固、变硬 ❷ 巩固、使稳固（关系/地位等）", example:"This win solidified her position.", root:"solid(固体)+ify(使) → 使变成固体 → 巩固" },
      { en:"present", phonetic:"/ˈpreznt/ /prɪˈzent/", pos:"adj./n./v.", meaning:"❶ adj. 在场的、出席的（be present at） ❷ adj. 当前的、现在的（at the present time） ❸ n. 礼物 ❹ n. 现在、目前（the present） ❺ v. 展示、呈现（present findings） ❻ v. 颁发、赠送（present an award） ❼ v. 引见、介绍（present sb to sb） ❽ v. 提出、呈现（present a problem/challenge）", example:"She presented her findings.", root:"pre(在前)+esse(存在) → 在眼前存在 → 出席/呈现/礼物" },
      { en:"fluent", phonetic:"/ˈfluːənt/", pos:"adj.", meaning:"❶ 流利的、流畅的（语言） ❷ 流畅的（动作/表达）", example:"She's fluent in three languages.", root:"fluere(流动) → 像水一样流出来 → 流利" },
      { en:"possible", phonetic:"/ˈpɑːsəbl/", pos:"adj./n.", meaning:"❶ adj. 可能的、有可能实现的 ❷ adj. 合理的、可接受的 ❸ n. 可能性（the possible）", example:"It's possible that it will rain.", root:"posse(能够) → 能够做到的 → 可能的" },
      { en:"intermediate", phonetic:"/ˌɪntərˈmiːdiət/", pos:"adj./n.", meaning:"❶ adj. 中级的、中间的 ❷ n. 中级水平者/中级课程", example:"This is for intermediate learners.", root:"inter(在之间)+medius(中间) → 夹在中间的 → 中级的" },
      { en:"advanced", phonetic:"/ədˈvænst/", pos:"adj.", meaning:"❶ 高级的、先进的 ❷ 深入的（阶段/水平） ❸ 年老的（年龄）", example:"She's in the advanced English class.", root:"advance(前进)的过去分词 → 已经走得很前面的 → 高级的" },
      { en:"customizable", phonetic:"/ˈkʌstəmaɪzəbl/", pos:"adj.", meaning:"可定制的、可按用户需求修改的", example:"The dashboard is fully customizable.", root:"custom(习惯/定制)+ize(使)+able(可) → 可以按习惯改的 → 可定制" },
      { en:"comfortable", phonetic:"/ˈkʌmftəbl/ /ˈkʌmfərtəbl/", pos:"adj.", meaning:"❶ 舒适的、舒服的 ❷ 自在的、放松的（comfortable with） ❸ 宽裕的（经济上，financially comfortable） ❹ 轻松获胜的（comfortable win）", example:"This sofa is very comfortable.", root:"com(加强)+fortis(强壮) → 有力量支撑 → 舒适/自在" },
      { en:"optional", phonetic:"/ˈɑːpʃənl/", pos:"adj.", meaning:"可选的、非强制的（不选也行）", example:"Attendance is optional.", root:"option(选择)+al → 可以选择要不要的 → 可选的" },
      { en:"beneficial", phonetic:"/ˌbenɪˈfɪʃl/", pos:"adj.", meaning:"有益的、有利的（对…有好处）", example:"Exercise is beneficial to health.", root:"bene(好)+facere(做) → 做好事 → 有益的" },
      { en:"less", phonetic:"/les/", pos:"adj./adv./det.", meaning:"❶ adj./det. 更少的、较少的 ❷ adv. 较少地、不如", example:"We have less time than I thought.", root:"古义: 更小的 → 数量上更少的 → less" },
      { en:"daily", phonetic:"/ˈdeɪli/", pos:"adj./adv./n.", meaning:"❶ adj. 每日的、日常的 ❷ adv. 每天 ❸ n. 日报", example:"Exercise is part of my daily routine.", root:"day(天)+ly(每) → 每天的 → 日常的" },
      { en:"without", phonetic:"/wɪˈðaʊt/", pos:"prep./adv.", meaning:"❶ prep. 没有、不带 ❷ adv. 在外面（古用法）", example:"He left without saying goodbye.", root:"with(有)+out(外) → 在有的范围之外 → 没有" },
      { en:"especially", phonetic:"/ɪˈspeʃəli/", pos:"adv.", meaning:"❶ 尤其、特别 ❷ 专门地、特意地", example:"I love fruit, especially mangoes.", root:"es(出)+special(特别) → 特别地从中突出 → 尤其" },
      { en:"on top of that", phonetic:"/ɑːn tɑːp əv ðæt/", pos:"phrase", meaning:"而且、更何况（在已有不好的事情上再加一层）", example:"I lost my wallet, and on top of that, my phone died.", root:"在已经有的(top)上面再加一层 → 而且/更何况", noAudio:true },
      { en:"whether", phonetic:"/ˈweðər/", pos:"conj.", meaning:"❶ 是否（引导间接疑问句或条件句） ❷ 不管…还是…（whether...or...）", example:"Whether you go or stay is up to you.", root:"古英语hwæther(两者中哪个) → 二选一 → 是否/不管…还是" },
      { en:"conclusion", phonetic:"/kənˈkluːʒn/", pos:"n.", meaning:"❶ 结论、推论 ❷ 结尾、结局 ❸ 缔结、达成（条约等）", example:"What conclusion did you reach?", root:"con(一起)+cludere(关闭) → 把论证收拢关上 → 结论" },
      { en:"description", phonetic:"/dɪˈskrɪpʃn/", pos:"n.", meaning:"❶ 描述、描写 ❷ 种类、类型（of a certain description）", example:"Give a brief description of the problem.", root:"de(向下)+scribere(写) → 写下来的细节 → 描述" },
      { en:"definition", phonetic:"/ˌdefɪˈnɪʃn/", pos:"n.", meaning:"❶ 定义、释义 ❷ 清晰度、鲜明度（图像/声音）", example:"Look up the definition of this word.", root:"de(完全)+finire(限定) → 严格划定边界 → 定义" }
    ]
  },
  {
    date: "📅 2026-05-18（43词）",
    words: [
      { en:"side", phonetic:"/saɪd/", pos:"n./adj./v.", meaning:"❶ n. 侧面、一边 ❷ n. 方面、立场 ❸ n. （身体/物体的）侧部 ❹ adj. 侧面的、次要的 ❺ v. 支持、站在…一边", example:"Choose a side and stick with it.", root:"古义: 宽而扁的面 → 物体/立场的某一侧 → 侧面/方面" },
      { en:"reroute", phonetic:"/ˌriːˈruːt/", pos:"v.", meaning:"改道、改变路线（使走另一条路）", example:"Traffic was rerouted due to the accident.", root:"re(重新)+route(路线) → 换一条路走 → 改道" },
      { en:"accident", phonetic:"/ˈæksɪdənt/", pos:"n.", meaning:"❶ 事故、意外事件 ❷ 偶然、意外（by accident）", example:"The accident happened at the intersection.", root:"ad(向)+cadere(落下) → 不该发生却落到头上的事 → 事故/意外" },
      { en:"different path than normal", phonetic:"/ˈdɪfrənt pæθ ðæn ˈnɔːrml/", pos:"phrase", meaning:"不同于平常的路（走了另外一条）", example:"We took a different path than normal to avoid traffic.", root:"不是平常(normal)走的那条路(path) → 绕道", noAudio:true },
      { en:"path", phonetic:"/pæθ/", pos:"n.", meaning:"❶ 小路、小径 ❷ 路线、途径 ❸ 轨迹（运动的）", example:"Follow the path through the forest.", root:"古英语pæth → 脚踩出来的路线 → 小径/途径" },
      { en:"spin", phonetic:"/spɪn/", pos:"v./n.", meaning:"❶ v. 快速旋转 ❷ v. 纺纱、吐丝 ❸ v. 编造（故事，spin a tale） ❹ v. 甩干（洗衣机） ❺ n. 旋转 ❻ n. 倾向性报道（政治，put a spin on） ❼ n. 兜风、短途出行（a spin in the car）", example:"The wheel started to spin.", root:"古义: 快速旋转(如纺锤) → 绕轴高速转动 → 转" },
      { en:"circle", phonetic:"/ˈsɜːrkl/", pos:"n./v.", meaning:"❶ n. 圆、圆圈 ❷ n. 圈子（社交/学术） ❸ v. 环绕、盘旋 ❹ v. 画圈标出", example:"The children sat in a circle.", root:"circus(圆环) → 没有角的闭合形状 → 圆" },
      { en:"windy", phonetic:"/ˈwɪndi/", pos:"adj.", meaning:"❶ 多风的、风大的 ❷ 弯曲的、蜿蜒的（道路，= winding）", example:"It's too windy to go sailing today.", root:"wind(风)+y → 风很多的 → 多风的" },
      { en:"electricity", phonetic:"/ɪˌlekˈtrɪsəti/", pos:"n.", meaning:"❶ 电、电力（能量形式，通过电线输送供照明/驱动等） ❷ 激动、紧张气氛（a feeling of excitement）", example:"The electricity was cut off during the storm.", root:"elektron(琥珀) → 琥珀摩擦生电 → 电" },
      { en:"sharp drop", phonetic:"/ʃɑːrp drɑːp/", pos:"phrase", meaning:"骤降、暴跌（温度/价格/数量等急剧下降）", example:"There was a sharp drop in temperature overnight.", root:"sharp(陡峭的)+drop(掉落) → 像悬崖一样垂直掉下去 → 骤降", compound:true },
      { en:"median", phonetic:"/ˈmiːdiən/", pos:"n./adj.", meaning:"❶ n. 中位数（统计学） ❷ n. 中央分隔带（道路） ❸ adj. 中间的、中值的", example:"The median income is lower than the average.", root:"medius(中间) → 正中间的那一个 → 中位数/中央隔离带" },
      { en:"dump truck", phonetic:"/ˈdʌmp trʌk/", pos:"n.", meaning:"自卸卡车、翻斗车（车厢可倾斜卸货）", example:"The dump truck unloaded the gravel.", root:"dump(倾倒)+truck(卡车) → 能把东西倒出来的卡车 → 翻斗车", compound:true },
      { en:"roundabout", phonetic:"/ˈraʊndəˌbaʊt/", pos:"n./adj.", meaning:"❶ n. 环形交叉路口（英式，美式常用traffic circle） ❷ n. 旋转木马 ❸ adj. 绕弯的、不直截了当的（a roundabout way）", example:"Take the roundabout instead of turning left.", root:"round(绕圈)+about(到处) → 绕一大圈 → 环形路口/绕弯的" },
      { en:"solar", phonetic:"/ˈsoʊlər/", pos:"adj.", meaning:"❶ 太阳的、来自太阳的 ❷ 利用太阳能的", example:"Solar panels convert sunlight into electricity.", root:"sol(太阳) → 来自太阳的 → 太阳的" },
      { en:"solar panel", phonetic:"/ˈsoʊlər ˈpænl/", pos:"n.", meaning:"太阳能电池板（将阳光转化为电能的板）", example:"We installed solar panels on the roof.", root:"solar(太阳的)+panel(板) → 用太阳光的板 → 太阳能板", compound:true },
      { en:"shoulder", phonetic:"/ˈʃoʊldər/", pos:"n./v.", meaning:"❶ n. 肩膀 ❷ n. 路肩（道路两侧的紧急停车带） ❸ v. 承担、肩负（责任等）", example:"He shouldered the responsibility for the team.", root:"古义: 承载重物的部位 → 肩膀 → 承担" },
      { en:"nozzle", phonetic:"/ˈnɑːzl/", pos:"n.", meaning:"❶ 喷嘴、管嘴 ❷ 加油枪嘴", example:"Fill up the tank and return the nozzle.", root:"古法语nose → 管子的「鼻子」→ 喷嘴" },
      { en:"fill up", phonetic:"/fɪl ʌp/", pos:"phrasal v.", meaning:"❶ 加满、装满 ❷ 填写（表格） ❸ 打发时间", example:"I need to fill up the car with gas.", root:"fill(填满)+up(到顶) → 填到最上面 → 加满", noAudio:true },
      { en:"sidewalk", phonetic:"/ˈsaɪdwɔːk/", pos:"n.", meaning:"人行道（美式英语，英式为pavement）", example:"Walk on the sidewalk, not the road.", root:"side(旁边)+walk(走道) → 路边用来走的 → 人行道" },
      { en:"stuff", phonetic:"/stʌf/", pos:"n./v.", meaning:"❶ n. 东西、物品（口语，不可数，不知名或不重要时用） ❷ n. 某活动的全套装备/用品（swimming stuff） ❸ n. 素材、特质（the right stuff） ❹ v. 塞满、填满（stuff into/with） ❺ v. 填充（食物，如火鸡） ❻ v. 让人吃撑（stuff oneself）", example:"Put your stuff in the back seat.", root:"古义: 塞进去的材料 → 不知名的杂七杂八 → 东西" },
      { en:"nightstand", phonetic:"/ˈnaɪtstænd/", pos:"n.", meaning:"床头柜（美式英语，英式为bedside table）", example:"Put the lamp on the nightstand.", root:"night(夜晚)+stand(架子) → 床头夜间用的架子 → 床头柜" },
      { en:"huge", phonetic:"/hjuːdʒ/", pos:"adj.", meaning:"❶ 巨大的、庞大的 ❷ 极大的、非常多的", example:"That's a huge difference.", root:"古法语ahuge → 大到让人敬畏 → 巨大的" },
      { en:"deadbolt lock", phonetic:"/ˈdedboʊlt lɑːk/", pos:"n.", meaning:"死栓锁、插销锁（需手动旋转才能开关的锁，比弹簧锁更安全）", example:"Always use the deadbolt lock at night.", root:"dead(死/固定)+bolt(插销)+lock → 死死插住不能弹回的锁 → 插销锁", compound:true },
      { en:"hallway", phonetic:"/ˈhɔːlweɪ/", pos:"n.", meaning:"走廊、过道（建筑内部的通道）", example:"Leave your shoes in the hallway.", root:"hall(大厅)+way(通道) → 穿过大厅的通道 → 走廊" },
      { en:"elevator", phonetic:"/ˈelɪveɪtər/", pos:"n.", meaning:"电梯、升降机（美式英语，英式为lift）", example:"Take the elevator to the fifth floor.", root:"elevare(举起) → 把人举上去的机器 → 电梯" },
      { en:"laundromat", phonetic:"/ˈlɔːndrəmæt/", pos:"n.", meaning:"自助洗衣店（投币使用洗衣机和烘干机）", example:"I go to the laundromat every Sunday.", root:"laundry(洗衣)+automatic(自动) → 自助洗衣 → 自助洗衣店" },
      { en:"plaza", phonetic:"/ˈplɑːzə/", pos:"n.", meaning:"❶ 广场、露天公共空间 ❷ 购物中心、商业区", example:"We met at the plaza in front of the library.", root:"拉丁语platea(宽阔空间) → 城市中的开阔地 → 广场" },
      { en:"religious", phonetic:"/rɪˈlɪdʒəs/", pos:"adj.", meaning:"❶ 宗教的、宗教上的 ❷ 虔诚的、笃信的 ❸ 极其认真的（口语：religious about punctuality）", example:"She's not very religious, but she respects all faiths.", root:"religio(绑定) → 与神灵绑在一起的 → 宗教的/虔诚的" },
      { en:"church", phonetic:"/tʃɜːrtʃ/", pos:"n.", meaning:"❶ 教堂（基督教礼拜场所） ❷ 教会、教派", example:"The church is on the corner of Main Street.", root:"古英语cirice → 基督徒聚会的建筑 → 教堂" },
      { en:"main park", phonetic:"/meɪn pɑːrk/", pos:"phrase", meaning:"主公园（城里最大或最主要的公园）", example:"Let's meet at the main park downtown.", root:"main(主要的)+park(公园) → 城里最重要的公园 → 主公园", compound:true },
      { en:"square", phonetic:"/skwer/", pos:"n./adj./v.", meaning:"❶ n. 广场 ❷ n. 正方形 ❸ n. 平方（数学） ❹ adj. 正方形的 ❺ adj. 公平的、正直的（fair and square） ❻ adj. 两清的、扯平的（we're square） ❼ v. 使成方形 ❽ v. 结清（账目，square up） ❾ v. 使一致、吻合（square with）", example:"The hotel is near the town square.", root:"古法语esquarre → 四条边一样长的形状 → 正方形/广场" },
      { en:"statue", phonetic:"/ˈstætʃuː/", pos:"n.", meaning:"雕像、塑像（人/动物的立体造型）", example:"There's a statue of the founder in the square.", root:"statuere(立起来) → 立在那里给人看的东西 → 雕像" },
      { en:"famous", phonetic:"/ˈfeɪməs/", pos:"adj.", meaning:"❶ 著名的、有名的 ❷ 极好的（口语）", example:"This restaurant is famous for its pizza.", root:"fama(传闻/名声) → 名声传遍各处的 → 著名的" },
      { en:"popular", phonetic:"/ˈpɑːpjələr/", pos:"adj.", meaning:"❶ 受欢迎的、流行的（popular with/among） ❷ 大众的、通俗的（popular music） ❸ 平民的、民众的（popular opinion）", example:"This is the most popular beach in town.", root:"populus(人民) → 受大众喜爱的 → 受欢迎的" },
      { en:"cathedral", phonetic:"/kəˈθiːdrəl/", pos:"n.", meaning:"大教堂（有主教座位的教堂，比普通church规模大、地位高）", example:"Notre-Dame is a famous cathedral in Paris.", root:"cathedra(座位) → 放主教宝座的教堂 → 大教堂" },
      { en:"tower", phonetic:"/ˈtaʊər/", pos:"n./v.", meaning:"❶ n. 塔、塔楼 ❷ n. 高楼（tower block） ❸ v. 高耸、超过（tower above/over）", example:"The TV tower overlooks the whole city.", root:"古法语tor → 向天空突出的高建筑 → 塔" },
      { en:"else", phonetic:"/els/", pos:"adj./adv.", meaning:"❶ adv. 其他、另外（用在疑问词/不定代词后） ❷ adj. 别的、其他的 ❸ 否则（or else）", example:"Do you want anything else?", root:"古英语elles → 其他的、别的 → 否则" },
      { en:"graffiti", phonetic:"/ɡrəˈfiːti/", pos:"n.", meaning:"涂鸦（在公共墙面上的未经许可的字画，不可数名词）", example:"The wall was covered in graffiti.", root:"graffiare(刮/刻) → 在墙上刻画的痕迹 → 涂鸦" },
      { en:"mural", phonetic:"/ˈmjʊrəl/", pos:"n.", meaning:"壁画（画在墙面上的大型画作，通常为官方委托创作）", example:"The city commissioned a mural for the side of the building.", root:"murus(墙) → 画在墙上的 → 壁画" },
      { en:"flood", phonetic:"/flʌd/", pos:"n./v.", meaning:"❶ n. 洪水、水灾 ❷ n. 大量、大批（a flood of letters） ❸ v. 淹没、泛滥 ❹ v. 大量涌入、充斥（flood the market） ❺ v. 涌上心头（memories came flooding back）", example:"The flood damaged many homes.", root:"古英语flod → 水漫过正常范围 → 洪水" },
      { en:"come down", phonetic:"/kʌm daʊn/", pos:"phrasal v.", meaning:"❶ 下来、降落 ❷ 下跌、降价 ❸ 坍塌、倒塌", example:"The rain is coming down hard.", root:"come(来)+down(下) → 从高处下来 → 下来/下跌", noAudio:true },
      { en:"completely", phonetic:"/kəmˈpliːtli/", pos:"adv.", meaning:"完全地、彻底地（百分之百，毫无保留）", example:"I completely forgot about the meeting.", root:"com(完全)+plere(填满)+ly → 一点空隙都不留 → 完全地" },
      { en:"spork", phonetic:"/spɔːrk/", pos:"n.", meaning:"叉勺（勺子和叉子的合体餐具，spoon + fork）", example:"They gave us a spork with the takeout meal.", root:"spoon(勺)+fork(叉)的混成词 → 又是勺又是叉 → 叉勺" }
    ]
  },
  {
    date: "📅 2026-05-20（58词）",
    words: [
      { en:"festival", phonetic:"/ˈfestəvl/", pos:"n.", meaning:"❶ 文化节、艺术节（一系列演出/活动，通常每年在同一地点举办） ❷ 节日、庆典日（人们停止工作庆祝特殊日子，常与宗教有关）", example:"There are many music festivals in summer.", root:"festum(节日) → 大家停下来庆祝的日子 → 节日/文化节" },
      { en:"historical", phonetic:"/hɪˈstɔːrɪkl/", pos:"adj.", meaning:"❶ 历史的、有关历史的 ❷ 基于史实的 ❸ 有历史意义的（区别于historic：historical指「关于历史的」，historic指「有历史意义的」）", example:"This is a historical building from the 1800s.", root:"historia(故事/记录) → 基于历史记录的 → 历史的" },
      { en:"center", phonetic:"/ˈsentər/", pos:"n./v.", meaning:"❶ n. 中心、中央 ❷ n. 活动中心、机构 ❸ n. 中锋（体育） ❹ v. 集中、以…为中心（center on/around）", example:"The hotel is in the city center.", root:"centrum(圆心/中心点) → 一切围绕的那个点 → 中心" },
      { en:"stair", phonetic:"/ster/", pos:"n.", meaning:"❶ 台阶、阶梯（单级） ❷ 楼梯（stairs，复数形式常用）", example:"Go up the stairs to the second floor.", root:"古英语stǣr → 一步步往上走的台阶 → 阶梯" },
      { en:"spiral", phonetic:"/ˈspaɪrəl/", pos:"n./adj./v.", meaning:"❶ n. 螺旋形 ❷ n. 不断恶化/上升的进程 ❸ adj. 螺旋的 ❹ v. 螺旋式上升/下降 ❺ v. 急剧恶化", example:"The staircase has a beautiful spiral design.", root:"spira(螺旋/线圈) → 像弹簧一样绕圈上升 → 螺旋" },
      { en:"bite", phonetic:"/baɪt/", pos:"v./n.", meaning:"❶ v. 咬、叮 ❷ v. 上当、咬钩 ❸ n. 咬一口 ❹ n. 叮咬的伤口 ❺ n. 一小口食物", example:"The mosquito bit me on the arm.", root:"古英语bītan → 用牙齿切入 → 咬" },
      { en:"rob", phonetic:"/rɑːb/", pos:"v.", meaning:"❶ 抢劫、掠夺 ❷ 使丧失（rob sb of sth）", example:"He was robbed on his way home.", root:"古诺斯语rauba → 剥夺别人的东西 → 抢劫" },
      { en:"gate", phonetic:"/ɡeɪt/", pos:"n.", meaning:"❶ 大门、栅栏门 ❷ 登机口 ❸ 闸门 ❹ 门票收入（口语）", example:"We waited at the airport gate.", root:"古英语ġeat → 围墙上的开口 → 大门" },
      { en:"light", phonetic:"/laɪt/", pos:"n./adj./v.", meaning:"❶ n. 光、光线 ❷ n. 灯、光源 ❸ n. 火柴、打火机（have you got a light?） ❹ adj. 轻的 ❺ adj. 浅色的 ❻ adj. 少量的、清淡的（light rain/light meal） ❼ adj. 睡眠浅的（light sleeper） ❽ v. 点燃、照亮（lit/lighted）", example:"Turn on the light, please.", root:"古英语lēoht → 让世界可见的东西 → 光/轻的" },
      { en:"camera", phonetic:"/ˈkæmərə/ /ˈkæmrə/", pos:"n.", meaning:"❶ 照相机、摄像机 ❷ 监控摄像头 ❸ 摄影组（camera crew）", example:"Don't forget to bring your camera.", root:"camera(房间/暗室) → 暗箱拍照的装置 → 相机" },
      { en:"sign", phonetic:"/saɪn/", pos:"n./v.", meaning:"❶ n. 标志、指示牌 ❷ n. 迹象、征兆（sign of） ❸ n. 手势、信号 ❹ n. 符号（数学/音乐） ❺ v. 签名、签字（sign a document） ❻ v. 签约（sign a contract/with a team）", example:"Follow the signs to the exit.", root:"signum(标记) → 用来指示或代表某物的 → 标志/签名" },
      { en:"intersection", phonetic:"/ˌɪntərˈsekʃn/", pos:"n.", meaning:"❶ 十字路口、交叉路口 ❷ 交叉点、交点 ❸ 交集（数学/逻辑）", example:"Turn left at the intersection.", root:"inter(之间)+secare(切) → 两条路互相切过的点 → 交叉路口" },
      { en:"empty", phonetic:"/ˈempti/", pos:"adj./v.", meaning:"❶ adj. 空的、没有内容的 ❷ adj. 空洞的、无意义的（empty words/promises） ❸ adj. 空虚的、饥饿的（empty stomach） ❹ v. 倒空、腾空（empty the trash）", example:"The room was completely empty.", root:"古英语ǣmettig → 里面什么都没有的 → 空的" },
      { en:"security", phonetic:"/sɪˈkjʊrəti/", pos:"n.", meaning:"❶ 安全、保障（保护免受攻击/危险） ❷ 安保措施、安保人员 ❸ 抵押品、担保物（金融） ❹ 证券、债券（securities）", example:"Airport security checked our bags.", root:"se(离开)+cura(担忧) → 不用担忧 → 安全/保障" },
      { en:"guard", phonetic:"/ɡɑːrd/", pos:"n./v.", meaning:"❶ n. 警卫、守卫 ❷ n. 卫兵、哨兵 ❸ n. 防守姿势（boxing: keep your guard up） ❹ v. 守卫、保卫 ❺ v. 防范、警惕（guard against）", example:"The guard stood at the entrance.", root:"gard(看守) → 守护入口的人 → 警卫" },
      { en:"break", phonetic:"/breɪk/", pos:"v./n.", meaning:"❶ v. 打破、弄碎 ❷ v. 违反（规则/法律/承诺） ❸ v. 中断、暂停（break the silence） ❹ v. 透露、公布（break the news） ❺ n. 休息、间歇 ❻ n. 破裂、裂口 ❼ n. 机会（口语：lucky break） ❽ n. 间歇、停顿（a break in the weather）", example:"Don't break the window.", root:"古英语brecan → 把完整的东西分开 → 打破" },
      { en:"law", phonetic:"/lɔː/", pos:"n.", meaning:"❶ 法律、法规 ❷ 法学、法律界 ❸ 规律、定律（自然/科学） ❹ 执法人员（the law）", example:"It's against the law to steal.", root:"古诺斯语lag → 让大家遵守的规则 → 法律" },
      { en:"giant", phonetic:"/ˈdʒaɪənt/", pos:"n./adj.", meaning:"❶ n. 巨人（传说中的） ❷ n. 大公司、巨头（商业/体育） ❸ adj. 巨大的、特大的", example:"A giant tree stood in the middle of the park.", root:"古希腊语gigas → 体型远超常人的存在 → 巨人" },
      { en:"vault", phonetic:"/vɔːlt/", pos:"n./v.", meaning:"❶ n. 金库、保险库（银行中厚墙铁门的房间） ❷ n. 地下墓室（教堂/墓地下的） ❸ n. 拱顶、穹顶 ❹ n. 撑杆跳（pole vault） ❺ v. 跳跃、跃过（用手撑着跳）", example:"The bank vault was locked overnight.", root:"volvere(卷/拱) → 拱形覆盖的空间 → 金库/拱顶" },
      { en:"mayor", phonetic:"/ˈmeɪər/ /ˈmer/", pos:"n.", meaning:"市长（城镇/城市的民选最高行政长官）", example:"The mayor gave a speech at the festival.", root:"maior(更大的) → 城镇里最大的官 → 市长" },
      { en:"Spain", phonetic:"/speɪn/", pos:"n.", meaning:"西班牙（欧洲西南部国家）", example:"She travelled to Spain last summer.", root:"拉丁语Hispania → 伊比利亚半岛国家 → 西班牙" },
      { en:"pedal", phonetic:"/ˈpedl/", pos:"n./v.", meaning:"❶ n. 踏板（自行车/钢琴/汽车） ❷ v. 踩踏板、骑自行车", example:"She pedalled hard up the hill.", root:"pes(脚) → 用脚踩的东西 → 踏板" },
      { en:"sushi bowl", phonetic:"/ˈsuːʃi boʊl/", pos:"n.", meaning:"寿司碗（寿司食材放在碗里的日式餐食，也叫poke bowl的变体）", example:"I ordered a sushi bowl for lunch.", root:"sushi(寿司)+bowl(碗) → 装在碗里的寿司 → 寿司碗", compound:true },
      { en:"arch", phonetic:"/ɑːrtʃ/", pos:"n./v./adj.", meaning:"❶ n. 拱、拱门（支撑上方重量的弧形结构） ❷ n. 拱形入口/纪念碑 ❸ n. 足弓 ❹ n. 拱形物（如眉弓） ❺ v. 成拱形、拱起 ❻ v. 弯曲（背部/眉毛） ❼ adj. 调皮的、狡黠的（arch smile）", example:"The bridge was built with stone arches.", root:"arcus(弧) → 弯成弧形的结构 → 拱门" },
      { en:"alleyway", phonetic:"/ˈæliweɪ/", pos:"n.", meaning:"小巷、窄巷（建筑物之间的狭窄通道，= alley）", example:"We walked down a narrow alleyway.", root:"alley(小巷)+way(路) → 建筑之间的窄路 → 小巷" },
      { en:"lick", phonetic:"/lɪk/", pos:"v./n.", meaning:"❶ v. 舔 ❷ v. 轻易击败（口语，lick sb） ❸ v. 克服、解决（lick a problem） ❹ n. 舔 ❺ n. 少量涂抹（a lick of paint）", example:"The dog licked my hand.", root:"古英语liccian → 用舌头触碰 → 舔" },
      { en:"express", phonetic:"/ɪkˈspres/", pos:"v./adj./n.", meaning:"❶ v. 表达、表述（thoughts/feelings） ❷ v. 快递发送 ❸ adj. 快速的、快递的（express delivery） ❹ adj. 明确的、确切的（express purpose） ❺ n. 快车、快运 ❻ n. 快递服务", example:"I find it hard to express my feelings.", root:"ex(出)+pressare(压) → 把里面的想法压出来 → 表达/快递" },
      { en:"desire", phonetic:"/dɪˈzaɪər/", pos:"n./v.", meaning:"❶ n. 渴望、欲望（strong desire） ❷ n. 性欲 ❸ v. 渴望、期望（desire to do sth） ❹ v. 要求、请求（formal）", example:"He has a strong desire to travel the world.", root:"de+siderare(观察星辰) → 仰望星空般地渴望 → 欲望" },
      { en:"bus", phonetic:"/bʌs/", pos:"n./v.", meaning:"❶ n. 公共汽车、巴士（沿固定路线行驶的大客车） ❷ n. 总线（计算机内部传输数据的线路） ❸ v. 乘公交车去 ❹ v. 用校车接送学生（busing） ❺ v. 收拾餐桌（餐厅）", example:"We took the bus to the festival.", root:"拉丁语omnibus(为大家所有人) → 载所有人的车 → 公交车" },
      { en:"light rail transit", phonetic:"/laɪt reɪl ˈtrænzɪt/", pos:"n.", meaning:"轻轨交通（城市轨道客运系统，比地铁轻、比有轨电车快，缩写LRT）", example:"The city is building a new light rail transit line.", root:"light(轻的)+rail(铁轨)+transit(过境) → 轻量级轨道交通 → 轻轨", compound:true },
      { en:"skin", phonetic:"/skɪn/", pos:"n./v.", meaning:"❶ n. 皮肤、表皮 ❷ n. 外皮、外壳（水果/动物的皮） ❸ n. 皮囊、外壳（sausage skin） ❹ v. 剥皮、去皮（skin a rabbit） ❺ v. 擦破皮（skinned my knee）", example:"She has sensitive skin.", root:"古英语scinn → 覆盖身体的外层 → 皮肤" },
      { en:"dairy product", phonetic:"/ˈderi ˈprɑːdʌkt/", pos:"n.", meaning:"乳制品（牛奶、奶酪、酸奶、黄油等）", example:"Cheese and yoghurt are dairy products.", root:"dairy(乳品)+product(产品) → 从牛奶加工出来的 → 乳制品", compound:true },
      { en:"product", phonetic:"/ˈprɑːdʌkt/", pos:"n.", meaning:"❶ 产品、制品（制造出来出售的东西） ❷ 产物、结果（the product of hard work） ❸ 乘积（数学：the product of 3 and 4）", example:"This is our best-selling product.", root:"pro(向前)+ducere(引导) → 引导产出的东西 → 产品" },
      { en:"section", phonetic:"/ˈsekʃn/", pos:"n./v.", meaning:"❶ n. 部分、区域 ❷ n. 章节（书的） ❸ n. 截面、剖面 ❹ n. 部门（组织中的） ❺ n. 切片（医学：a section of tissue） ❻ v. 切开、分区 ❼ v. 将…强行留院（精神病患者，section sb）", example:"The book is divided into three sections.", root:"secare(切) → 从整体上切下来的一块 → 部分/章节" },
      { en:"dry", phonetic:"/draɪ/", pos:"adj./v.", meaning:"❶ adj. 干的、干燥的 ❷ adj. 无甜味的（酒） ❸ adj. 枯燥的、无趣的 ❹ v. 弄干、变干", example:"Hang the clothes outside to dry.", root:"古英语drūge → 没有水分的 → 干的" },
      { en:"check out", phonetic:"/tʃek aʊt/", pos:"phrasal v.", meaning:"❶ 查看、了解（口语：去试试/看看） ❷ 退房（酒店） ❸ 结账离开 ❹ 借出（图书馆）", example:"You should check out that new restaurant.", root:"check(核实)+out(出去) → 核实完离开 → 退房/查看", noAudio:true },
      { en:"suit jacket", phonetic:"/suːt ˈdʒækɪt/", pos:"n.", meaning:"西装外套（与西裤配套的上装）", example:"He wore a dark suit jacket to the interview.", root:"suit(套装)+jacket(外套) → 西装套装中的上装 → 西装外套", compound:true },
      { en:"might", phonetic:"/maɪt/", pos:"modal v./n.", meaning:"❶ modal v. 可能、也许（表示可能性，比may更不确定） ❷ modal v. may的过去式（间接引语中） ❸ modal v. 委婉建议（You might try…） ❹ modal v. 表示不满（You might at least help!） ❺ n. 力量、威力（with all one's might）", example:"It might rain later.", root:"古英语mihte → 可能存在的力量 → 也许(可能性)/力量" },
      { en:"raw", phonetic:"/rɔː/", pos:"adj.", meaning:"❶ 生的、未烹煮的 ❷ 未加工的、天然状态的（raw material/sugar） ❸ 原始的、未经整理的（raw data） ❹ 强烈而未加控制的（raw emotion/talent） ❺ 红肿疼痛的（皮肤因摩擦/感染）", example:"I prefer raw vegetables in my salad.", root:"古英语hrēaw → 未经任何处理的原始状态 → 生的/原始的" },
      { en:"stall", phonetic:"/stɔːl/", pos:"n./v.", meaning:"❶ n. 摊位、售货亭（市场的） ❷ n. 畜栏、隔间（农场） ❸ n. 淋浴间/厕所隔间 ❹ n. （教堂）唱诗班座位 ❺ n. （车辆）熄火 ❻ n. （飞机）失速 ❼ v. （发动机）熄火 ❽ v. 拖延、推诿（stall for time） ❾ v. 使搁置、使停滞", example:"We bought fruit from a market stall.", root:"stallum(站立的地方) → 站着卖东西的位置 → 摊位" },
      { en:"blender", phonetic:"/ˈblendər/", pos:"n.", meaning:"搅拌机、榨汁机（厨房电器，用于打碎和混合食物）", example:"She made a smoothie in the blender.", root:"blend(混合)+er(器) → 把东西混在一起的机器 → 搅拌机" },
      { en:"sausage", phonetic:"/ˈsɔːsɪdʒ/", pos:"n.", meaning:"香肠（碎肉加调料灌入肠衣制成，可数）", example:"We had sausages and eggs for breakfast.", root:"salsus(加盐的) → 用盐腌制的碎肉灌肠 → 香肠" },
      { en:"cut up", phonetic:"/kʌt ʌp/", pos:"phrasal v.", meaning:"❶ 切碎、切成小块 ❷ 伤心、难受（口语：cut up about）", example:"Cut up the vegetables before putting them in the soup.", root:"cut(切)+up(彻底) → 彻底切成碎块 → 切碎", noAudio:true },
      { en:"pork", phonetic:"/pɔːrk/", pos:"n.", meaning:"猪肉（不可数名词，指食材；与pig的区别：pig是活猪，pork是猪肉）", example:"We had roast pork for dinner.", root:"拉丁语porcus(猪) → 猪身上的肉(区别于活猪pig) → 猪肉" },
      { en:"crisp", phonetic:"/krɪsp/", pos:"adj./n./v.", meaning:"❶ adj. 脆的、酥脆的 ❷ adj. 清爽的、干冷的（天气） ❸ adj. 干净利落的、简洁的（crisp writing） ❹ n. 薯片（英式，= potato chip） ❺ v. 变脆、使变脆", example:"The skin on the roast pork was perfectly crisp.", root:"古英语crisp → 咬下去咔嚓响的 → 脆的" },
      { en:"extreme", phonetic:"/ɪkˈstriːm/", pos:"adj./n.", meaning:"❶ adj. 极端的、极度的 ❷ adj. 末端的、尽头的 ❸ n. 极端、极端情况 ❹ n. 极端的行为/观点（go to extremes）", example:"The weather here is extreme in summer.", root:"extremus(最外面的) → 离正常范围最远的 → 极端的" },
      { en:"hairdresser", phonetic:"/ˈherdresər/", pos:"n.", meaning:"理发师、美发师（为顾客剪发、染发、做造型的人）", example:"She's been going to the same hairdresser for years.", root:"hair(头发)+dresser(打理的人) → 给头发做造型的人 → 理发师" },
      { en:"butcher", phonetic:"/ˈbʊtʃər/", pos:"n./v.", meaning:"❶ n. 屠夫、肉贩 ❷ n. 菜刀手、搞砸的人（口语：a real butcher） ❸ v. 屠宰 ❹ v. 粗劣地弄、搞砸（butcher a song）", example:"We buy our meat from the local butcher.", root:"bouchier(屠夫) → 杀动物卖肉的人 → 屠夫" },
      { en:"peanut butter", phonetic:"/ˈpiːnʌt ˈbʌtər/", pos:"n.", meaning:"花生酱（花生磨成的酱，不可数）", example:"Peanut butter and jelly is a classic sandwich.", root:"peanut(花生)+butter(黄油状酱) → 花生磨成的酱 → 花生酱", compound:true },
      { en:"set up", phonetic:"/set ʌp/", pos:"phrasal v.", meaning:"❶ 建立、创办 ❷ 搭建、安装 ❸ 安排、策划 ❹ 陷害（口语：set somebody up）", example:"They set up a stall at the market.", root:"set(放置)+up(立起来) → 把东西立起来准备好 → 建立/搭建", noAudio:true },
      { en:"tent", phonetic:"/tent/", pos:"n./v.", meaning:"❶ n. 帐篷 ❷ v. 搭帐篷、宿营", example:"We pitched the tent by the river.", root:"tendere(拉伸) → 用布拉伸搭起的 shelter → 帐篷" },
      { en:"structure", phonetic:"/ˈstrʌktʃər/", pos:"n./v.", meaning:"❶ n. 结构、构造（the structure of the atom） ❷ n. 建筑物（a tall structure） ❸ v. 组织、安排（structure an essay）", example:"The structure of this building is impressive.", root:"struere(建造) → 建造出来的框架 → 结构" },
      { en:"grow", phonetic:"/ɡroʊ/", pos:"v.", meaning:"❶ 生长、成长 ❷ 种植、栽培（grow tomatoes） ❸ 增长、扩大（grow the business） ❹ 变得、逐渐变成（grow + adj. grow tired） ❺ 留长（grow a beard）", example:"Plants grow faster in spring.", root:"古英语grōwan → 从小变大 → 生长" },
      { en:"farm", phonetic:"/fɑːrm/", pos:"n./v.", meaning:"❶ n. 农场、养殖场 ❷ v. 务农、种田 ❸ v. 养殖、培育（farm fish/shrimp）", example:"They live on a dairy farm.", root:"古英语feorm(租/口粮) → 产出口粮的地方 → 农场" },
      { en:"shell", phonetic:"/ʃel/", pos:"n./v.", meaning:"❶ n. 壳、贝壳（蛋壳/贝壳/龟壳） ❷ n. 炮弹、弹壳 ❸ n. 空壳、框架（仅剩外壳的东西） ❹ v. 剥壳、去壳（shell peas） ❺ v. 炮击、轰炸（shell a city）", example:"We spent the afternoon shelling peas.", root:"古英语sciell → 覆盖在外的硬层 → 壳" },
      { en:"plantain", phonetic:"/ˈplæntɪn/", pos:"n.", meaning:"大蕉、烹饪蕉（类似香蕉但更大更硬，通常需烹饪后食用，是拉美/加勒比/非洲的主食）", example:"Fried plantain is a popular side dish in many countries.", root:"planta(脚掌) → 叶子像脚掌一样宽的蕉 → 大蕉" },
      { en:"wood pallet", phonetic:"/wʊd ˈpælɪt/", pos:"n.", meaning:"木托盘、木栈板（用于堆放和搬运货物的木质平台）", example:"The goods were stacked on wood pallets in the warehouse.", root:"wood(木)+pallet(托盘) → 木质搬运平台 → 木托盘", compound:true },
      { en:"transport", phonetic:"/ˈtrænspɔːrt/", pos:"n./v.", meaning:"❶ n. 交通系统、运输方式 ❷ n. 交通工具 ❸ v. 运输、运送 ❹ v. 使身临其境（be transported）", example:"Public transport is very convenient in this city.", root:"trans(跨越)+portare(携带) → 把东西带过去 → 运输" }
    ]
  }
];
