// vocab-data.js — 英语词汇数据
// 新增日期只需在下方数组追加一个对象，然后刷新 HTML 即可
// 格式：{ date: "显示日期", words: [ {en, phonetic, pos, meaning, example}, ... ] }

const VOCAB_DATA = [
  {
    date: "📅 2026-05-17（47词）",
    words: [
      { en:"pronunciation", phonetic:"/prəˌnʌnsiˈeɪʃən/", pos:"n.", meaning:"发音——词撞耳朵的方式", example:"Your pronunciation of 'th' needs work." },
      { en:"comprehension", phonetic:"/ˌkɒmprɪˈhenʃən/", pos:"n.", meaning:"理解——把意思抓进脑子", example:"The test has a listening comprehension section." },
      { en:"sentence structure", phonetic:"/ˈsentəns ˈstrʌktʃər/", pos:"n.", meaning:"句结构——撑起句子的骨架", example:"Vary sentence structure for better writing." },
      { en:"method", phonetic:"/ˈmeθəd/", pos:"n.", meaning:"方法——有计划的路径", example:"The method we used was surveys." },
      { en:"comprehensible input", phonetic:"/ˌkɒmprɪˈhensɪbl ˈɪnpʊt/", pos:"n.", meaning:"可理解输入(i+1)", example:"Comprehensible input is key in Krashen's theory." },
      { en:"lesson", phonetic:"/ˈlesən/", pos:"n.", meaning:"课程/教训——让你学到东西", example:"That failure taught me a valuable lesson." },
      { en:"adventure", phonetic:"/ədˈventʃər/", pos:"n.", meaning:"冒险——主动走进未知", example:"We had many adventures in South America." },
      { en:"goal", phonetic:"/ɡoʊl/", pos:"n.", meaning:"目标/球门——你瞄准的门柱", example:"My goal is to become fluent." },
      { en:"quiz", phonetic:"/kwɪz/", pos:"n./v.", meaning:"小测验——突然甩过来的几道题", example:"We have a quiz on chapter 3." },
      { en:"chance", phonetic:"/tʃɑːns/", pos:"n./v.", meaning:"机会/运气——骰子落地那一面", example:"This is your chance to prove yourself." },
      { en:"software", phonetic:"/ˈsɒftweər/", pos:"n.", meaning:"软件——让硬件有灵魂的代码", example:"Install the software first." },
      { en:"confusion", phonetic:"/kənˈfjuːʒən/", pos:"n.", meaning:"困惑/混乱——搅成一锅", example:"There was confusion about the time." },
      { en:"term", phonetic:"/tɜːm/", pos:"n.", meaning:"术语/学期/条款——画圈圈住概念", example:"What does this term mean?" },
      { en:"visual", phonetic:"/ˈvɪʒuəl/", pos:"n./adj.", meaning:"视觉的——给人看的", example:"The visuals drove the point home." },
      { en:"routine", phonetic:"/ruːˈtiːn/", pos:"n./adj.", meaning:"常规——同一条路踩出了沟", example:"Reading is my daily routine." },
      { en:"stick", phonetic:"/stɪk/", pos:"n./v.", meaning:"棍/粘/坚持——棍子能干的所有事", example:"Stick to the plan." },
      { en:"part", phonetic:"/pɑːt/", pos:"n./v.", meaning:"部分/角色——从整体切下来", example:"She is a part of our team." },
      { en:"prompt", phonetic:"/prɒmpt/", pos:"n./adj./v.", meaning:"提示/促使——摆在你面前", example:"Write a better prompt for better results." },
      { en:"tense", phonetic:"/tens/", pos:"n./adj.", meaning:"时态/紧张的——被拉紧的", example:"English has 12 tenses." },
      { en:"design", phonetic:"/dɪˈzaɪn/", pos:"v./n.", meaning:"设计——动手前先做标记", example:"The app is designed to help beginners." },
      { en:"reach", phonetic:"/riːtʃ/", pos:"v./n.", meaning:"到达/够到——手伸出去碰到", example:"We reached the summit at dawn." },
      { en:"study", phonetic:"/ˈstʌdi/", pos:"v./n.", meaning:"学习/研究——带着饥渴去追", example:"She studies English every day." },
      { en:"practice", phonetic:"/ˈpræktɪs/", pos:"v./n.", meaning:"练习——做到手比脑子快", example:"Practice makes perfect." },
      { en:"stick around", phonetic:"/stɪk əˈraʊnd/", pos:"v.", meaning:"留下来——粘在原地不走", example:"Stick around until you reach your goals." },
      { en:"allow", phonetic:"/əˈlaʊ/", pos:"v.", meaning:"允许/使能够——开绿灯", example:"Smoking is not allowed here." },
      { en:"reinforce", phonetic:"/ˌriːɪnˈfɔːs/", pos:"v.", meaning:"加强/增援——再灌一把力", example:"This data reinforces our conclusion." },
      { en:"explain", phonetic:"/ɪkˈspleɪn/", pos:"v.", meaning:"解释——铺平了让你看清楚", example:"Let me explain it to you." },
      { en:"ensure", phonetic:"/ɪnˈʃʊər/", pos:"v.", meaning:"确保——让结果跑不掉", example:"Ensure that all doors are locked." },
      { en:"solidify", phonetic:"/səˈlɪdɪfaɪ/", pos:"v.", meaning:"使凝固/巩固——把软的冻硬", example:"This win solidified her position." },
      { en:"present", phonetic:"/ˈprezənt/ /prɪˈzent/", pos:"adj./n./v.", meaning:"在场/现在/展示——站在前面", example:"She presented her findings." },
      { en:"fluent", phonetic:"/ˈfluːənt/", pos:"adj.", meaning:"流利的——话像水流", example:"She's fluent in three languages." },
      { en:"possible", phonetic:"/ˈpɒsəbl/", pos:"adj.", meaning:"可能的——有能力成为现实", example:"It's possible that it will rain." },
      { en:"intermediate", phonetic:"/ˌɪntərˈmiːdiət/", pos:"adj./n.", meaning:"中级的——夹在中间", example:"This is for intermediate learners." },
      { en:"advanced", phonetic:"/ədˈvɑːnst/", pos:"adj.", meaning:"高级的——已经走到前面", example:"She's in the advanced English class." },
      { en:"customizable", phonetic:"/ˈkʌstəmaɪzəbl/", pos:"adj.", meaning:"可定制的——能按你的习惯改", example:"The dashboard is fully customizable." },
      { en:"comfortable", phonetic:"/ˈkʌmftəbəl/", pos:"adj.", meaning:"舒适的/自在的——给你撑腰", example:"This sofa is very comfortable." },
      { en:"optional", phonetic:"/ˈɒpʃənl/", pos:"adj.", meaning:"可选的——选不选随你", example:"Attendance is optional." },
      { en:"beneficial", phonetic:"/ˌbenɪˈfɪʃəl/", pos:"adj.", meaning:"有益的——给你做了好事", example:"Exercise is beneficial to health." },
      { en:"less", phonetic:"/les/", pos:"adj./adv.", meaning:"更少/减去", example:"We have less time than I thought." },
      { en:"daily", phonetic:"/ˈdeɪli/", pos:"adj./adv.", meaning:"每日的——日出就来", example:"Exercise is part of my daily routine." },
      { en:"without", phonetic:"/wɪˈðaʊt/", pos:"prep./adv.", meaning:"没有/在外面", example:"He left without saying goodbye." },
      { en:"especially", phonetic:"/ɪˈspeʃəli/", pos:"adv.", meaning:"尤其——单独挑出来说", example:"I love fruit, especially mangoes." },
      { en:"on top of that", phonetic:"/ɒn tɒp əv ðæt/", pos:"phrase", meaning:"而且/更何况——再叠一层", example:"I lost my wallet, and on top of that, my phone died." },
      { en:"whether", phonetic:"/ˈweðər/", pos:"conj.", meaning:"是否——两条路摆在面前", example:"Whether you go or stay is up to you." },
      { en:"conclusion", phonetic:"/kənˈkluːʒən/", pos:"n.", meaning:"结论——走到路的尽头", example:"What conclusion did you reach?" },
      { en:"description", phonetic:"/dɪˈskrɪpʃən/", pos:"n.", meaning:"描述——用文字把东西画出来", example:"Give a brief description of the problem." },
      { en:"definition", phonetic:"/ˌdefɪˈnɪʃən/", pos:"n.", meaning:"定义——画出边界说清是什么", example:"Look up the definition of this word." }
    ]
  },
  {
    date: "📅 2026-05-18（43词）",
    words: [
      { en:"side", phonetic:"/saɪd/", pos:"n./adj.", meaning:"侧面/一边——从中间切开看到的那面", example:"Choose a side and stick with it." },
      { en:"reroute", phonetic:"/ˌriːˈruːt/", pos:"v.", meaning:"改道——原路堵了，换条路走", example:"Traffic was rerouted due to the accident." },
      { en:"accident", phonetic:"/ˈæksɪdənt/", pos:"n.", meaning:"事故/意外——没打算却发生了", example:"The accident happened at the intersection." },
      { en:"different path than normal", phonetic:"/ˈdɪfrənt pɑːθ ðæn ˈnɔːrml/", pos:"phrase", meaning:"不同于往常的路——走了另外一条", example:"We took a different path than normal to avoid traffic." },
      { en:"path", phonetic:"/pɑːθ/", pos:"n.", meaning:"小路/路径——脚踩出来的轨迹", example:"Follow the path through the forest." },
      { en:"spin", phonetic:"/spɪn/", pos:"v./n.", meaning:"旋转——绕着自己转", example:"The wheel started to spin." },
      { en:"circle", phonetic:"/ˈsɜːrkl/", pos:"n./v.", meaning:"圆/绕圈——没有终点的环", example:"The children sat in a circle." },
      { en:"windy", phonetic:"/ˈwɪndi/", pos:"adj.", meaning:"多风的——风一直推着你走", example:"It's too windy to go sailing today." },
      { en:"electricity", phonetic:"/ɪˌlekˈtrɪsɪti/", pos:"n.", meaning:"电——看不见但能点亮一切的力量", example:"The electricity was cut off during the storm." },
      { en:"sharp drop", phonetic:"/ʃɑːrp drɑːp/", pos:"phrase", meaning:"骤降——像刀一样直直切下去", example:"There was a sharp drop in temperature overnight." },
      { en:"median", phonetic:"/ˈmiːdiən/", pos:"n./adj.", meaning:"中位数/中间的——正中间那条线", example:"The median income is lower than the average." },
      { en:"dump truck", phonetic:"/dʌmp trʌk/", pos:"n.", meaning:"自卸卡车——能翻斗倒货的大车", example:"The dump truck unloaded the gravel." },
      { en:"roundabout", phonetic:"/ˈraʊndəbaʊt/", pos:"n./adj.", meaning:"环岛/绕弯的——转一圈才到", example:"Take the roundabout instead of turning left." },
      { en:"solar", phonetic:"/ˈsoʊlər/", pos:"adj.", meaning:"太阳的——跟太阳借来的", example:"Solar panels convert sunlight into electricity." },
      { en:"solar panel", phonetic:"/ˈsoʊlər ˈpænl/", pos:"n.", meaning:"太阳能板——把阳光变成电的板子", example:"We installed solar panels on the roof." },
      { en:"shoulder", phonetic:"/ˈʃoʊldər/", pos:"n./v.", meaning:"肩膀/承担——扛在肩上的东西", example:"He shouldered the responsibility for the team." },
      { en:"nozzle", phonetic:"/ˈnɑːzl/", pos:"n.", meaning:"喷嘴——管子末端的嘴", example:"Fill up the tank and return the nozzle." },
      { en:"fill up", phonetic:"/fɪl ʌp/", pos:"v.", meaning:"加满/填满——灌到满为止", example:"I need to fill up the car with gas." },
      { en:"sidewalk", phonetic:"/ˈsaɪdwɔːk/", pos:"n.", meaning:"人行道——走路的那条边", example:"Walk on the sidewalk, not the road." },
      { en:"stuff", phonetic:"/stʌf/", pos:"n./v.", meaning:"东西/塞满——一堆说不清的玩意儿", example:"Put your stuff in the back seat." },
      { en:"nightstand", phonetic:"/ˈnaɪtstænd/", pos:"n.", meaning:"床头柜——床边站着的小柜子", example:"Put the lamp on the nightstand." },
      { en:"huge", phonetic:"/hjuːdʒ/", pos:"adj.", meaning:"巨大的——大到你抬头看", example:"That's a huge difference." },
      { en:"deadbolt lock", phonetic:"/ˈdedboʊlt lɒk/", pos:"n.", meaning:"死栓锁——推到底才锁死的锁", example:"Always use the deadbolt lock at night." },
      { en:"hallway", phonetic:"/ˈhɔːlweɪ/", pos:"n.", meaning:"走廊——房间之间那条窄路", example:"Leave your shoes in the hallway." },
      { en:"elevator", phonetic:"/ˈelɪveɪtər/", pos:"n.", meaning:"电梯——把你举上去的箱子", example:"Take the elevator to the fifth floor." },
      { en:"laundromat", phonetic:"/ˈlɔːndrəmæt/", pos:"n.", meaning:"自助洗衣店——投币转圈的地方", example:"I go to the laundromat every Sunday." },
      { en:"plaza", phonetic:"/ˈplɑːzə/", pos:"n.", meaning:"广场/购物中心——城市里的空地", example:"We met at the plaza in front of the library." },
      { en:"religious", phonetic:"/rɪˈlɪdʒəs/", pos:"adj.", meaning:"宗教的——跟信仰绑在一起", example:"She's not very religious, but she respects all faiths." },
      { en:"church", phonetic:"/tʃɜːrtʃ/", pos:"n.", meaning:"教堂——信徒聚在一起的房子", example:"The church is on the corner of Main Street." },
      { en:"main park", phonetic:"/meɪn pɑːrk/", pos:"phrase", meaning:"主公园——城里最大的那片绿地", example:"Let's meet at the main park downtown." },
      { en:"square", phonetic:"/skweər/", pos:"n./adj./v.", meaning:"广场/正方形/平方——四边一样齐", example:"The hotel is near the town square." },
      { en:"statue", phonetic:"/ˈstætʃuː/", pos:"n.", meaning:"雕像——石头刻出来站着不动的人", example:"There's a statue of the founder in the square." },
      { en:"famous", phonetic:"/ˈfeɪməs/", pos:"adj.", meaning:"著名的——所有人都知道的名字", example:"This restaurant is famous for its pizza." },
      { en:"popular", phonetic:"/ˈpɑːpjʊlər/", pos:"adj.", meaning:"受欢迎的——大家都往那边涌", example:"This is the most popular beach in town." },
      { en:"cathedral", phonetic:"/kəˈθiːdrəl/", pos:"n.", meaning:"大教堂——教堂里的老大哥", example:"Notre-Dame is a famous cathedral in Paris." },
      { en:"tower", phonetic:"/ˈtaʊər/", pos:"n./v.", meaning:"塔/高耸——往上捅破天的东西", example:"The TV tower overlooks the whole city." },
      { en:"else", phonetic:"/els/", pos:"adj./adv.", meaning:"其他/否则——除了这个还剩什么", example:"Do you want anything else?" },
      { en:"graffiti", phonetic:"/ɡrəˈfiːti/", pos:"n.", meaning:"涂鸦——墙上偷偷画的字和画", example:"The wall was covered in graffiti." },
      { en:"mural", phonetic:"/ˈmjʊərəl/", pos:"n.", meaning:"壁画——整面墙都是画布", example:"The city commissioned a mural for the side of the building." },
      { en:"flood", phonetic:"/flʌd/", pos:"n./v.", meaning:"洪水/淹没——水到处都是", example:"The flood damaged many homes." },
      { en:"come down", phonetic:"/kʌm daʊn/", pos:"v.", meaning:"下来/降落——从高处落到低处", example:"The rain is coming down hard." },
      { en:"completely", phonetic:"/kəmˈpliːtli/", pos:"adv.", meaning:"完全地——一点不留的", example:"I completely forgot about the meeting." },
      { en:"spork", phonetic:"/spɔːrk/", pos:"n.", meaning:"叉勺——勺子和叉子合体", example:"They gave us a spork with the takeout meal." }
    ]
  },
  {
    date: "📅 2026-05-20（58词）",
    words: [
      { en:"festival", phonetic:"/ˈfestɪvəl/", pos:"n.", meaning:"节日/庆典——人们聚在一起庆祝的日子", example:"There are many music festivals in summer." },
      { en:"historical", phonetic:"/hɪˈstɒrɪkəl/", pos:"adj.", meaning:"历史的——跟过去绑在一起的", example:"This is a historical building from the 1800s." },
      { en:"center", phonetic:"/ˈsentər/", pos:"n./v.", meaning:"中心/居中——所有东西围着它转", example:"The hotel is in the city center." },
      { en:"stair", phonetic:"/steər/", pos:"n.", meaning:"楼梯/台阶——脚一步步踩上去的", example:"Go up the stairs to the second floor." },
      { en:"spiral", phonetic:"/ˈspaɪrəl/", pos:"n./adj./v.", meaning:"螺旋——转着圈往上或往下", example:"The staircase has a beautiful spiral design." },
      { en:"bite", phonetic:"/baɪt/", pos:"v./n.", meaning:"咬/叮——牙齿切进去", example:"The mosquito bit me on the arm." },
      { en:"rob", phonetic:"/rɒb/", pos:"v.", meaning:"抢劫——暴力把你的东西夺走", example:"He was robbed on his way home." },
      { en:"gate", phonetic:"/ɡeɪt/", pos:"n.", meaning:"大门/入口——控制进出的一道关", example:"We waited at the airport gate." },
      { en:"light", phonetic:"/laɪt/", pos:"n./adj./v.", meaning:"光/轻的/点燃——照亮黑暗的那个东西", example:"Turn on the light, please." },
      { en:"camera", phonetic:"/ˈkæmərə/", pos:"n.", meaning:"照相机——把瞬间冻住的盒子", example:"Don't forget to bring your camera." },
      { en:"sign", phonetic:"/saɪn/", pos:"n./v.", meaning:"标志/签名——告诉你该往哪走的记号", example:"Follow the signs to the exit." },
      { en:"intersection", phonetic:"/ˌɪntərˈsekʃn/", pos:"n.", meaning:"十字路口——两条路交叉的地方", example:"Turn left at the intersection." },
      { en:"empty", phonetic:"/ˈempti/", pos:"adj./v.", meaning:"空的/倒空——里面什么都没有", example:"The room was completely empty." },
      { en:"security", phonetic:"/sɪˈkjʊərəti/", pos:"n.", meaning:"安全/安保——不让坏事发生的防护", example:"Airport security checked our bags." },
      { en:"guard", phonetic:"/ɡɑːrd/", pos:"n./v.", meaning:"守卫/警卫——站在那里不让坏人进来", example:"The guard stood at the entrance." },
      { en:"break", phonetic:"/breɪk/", pos:"v./n.", meaning:"打破/中断——把完整的东西弄碎", example:"Don't break the window." },
      { en:"law", phonetic:"/lɔː/", pos:"n.", meaning:"法律/法则——所有人必须遵守的规则", example:"It's against the law to steal." },
      { en:"giant", phonetic:"/ˈdʒaɪənt/", pos:"n./adj.", meaning:"巨人/巨大的——比周围的大一圈", example:"A giant tree stood in the middle of the park." },
      { en:"vault", phonetic:"/vɔːlt/", pos:"n./v.", meaning:"金库/拱顶——厚重铁门后面的保险空间", example:"The bank vault was locked overnight." },
      { en:"mayor", phonetic:"/meɪər/", pos:"n.", meaning:"市长——一座城市的头儿", example:"The mayor gave a speech at the festival." },
      { en:"Spain", phonetic:"/speɪn/", pos:"n.", meaning:"西班牙——欧洲南部的国家", example:"She travelled to Spain last summer." },
      { en:"pedal", phonetic:"/ˈpedl/", pos:"n./v.", meaning:"踏板/踩踏板——脚踩着让它转的动力", example:"She pedalled hard up the hill." },
      { en:"sushi bowl", phonetic:"/ˈsuːʃi boʊl/", pos:"n.", meaning:"寿司碗——寿司装在碗里的一餐", example:"I ordered a sushi bowl for lunch." },
      { en:"arch", phonetic:"/ɑːrtʃ/", pos:"n./v.", meaning:"拱/拱门——弯成弧形撑住上面的重量", example:"The bridge was built with stone arches." },
      { en:"alleyway", phonetic:"/ˈæliweɪ/", pos:"n.", meaning:"小巷/窄道——楼与楼之间那条窄窄的路", example:"We walked down a narrow alleyway." },
      { en:"lick", phonetic:"/lɪk/", pos:"v./n.", meaning:"舔——舌头划过去", example:"The dog licked my hand." },
      { en:"express", phonetic:"/ɪkˈspres/", pos:"v./adj./n.", meaning:"表达/快速的——把心里的话挤出来", example:"I find it hard to express my feelings." },
      { en:"desire", phonetic:"/dɪˈzaɪər/", pos:"n./v.", meaning:"欲望/渴望——心里那股挡不住的想要", example:"He has a strong desire to travel the world." },
      { en:"bus", phonetic:"/bʌs/", pos:"n./v.", meaning:"公共汽车/乘公交——装一车人一起走", example:"We took the bus to the festival." },
      { en:"light rail transit", phonetic:"/laɪt reɪl ˈtrænsɪt/", pos:"n.", meaning:"轻轨交通——比地铁轻比公交快的轨道车", example:"The city is building a new light rail transit line." },
      { en:"skin", phonetic:"/skɪn/", pos:"n./v.", meaning:"皮肤/剥皮——包住身体的那层壳", example:"She has sensitive skin." },
      { en:"dairy product", phonetic:"/ˈderi ˈprɑːdʌkt/", pos:"n.", meaning:"乳制品——从牛奶变出来的食物", example:"Cheese and yoghurt are dairy products." },
      { en:"product", phonetic:"/ˈprɑːdʌkt/", pos:"n.", meaning:"产品/产物——被制造出来的东西", example:"This is our best-selling product." },
      { en:"section", phonetic:"/ˈsekʃn/", pos:"n.", meaning:"部分/区域——从整体切出来的一块", example:"The book is divided into three sections." },
      { en:"dry", phonetic:"/draɪ/", pos:"adj./v.", meaning:"干的/弄干——没有一滴水", example:"Hang the clothes outside to dry." },
      { en:"check out", phonetic:"/tʃek aʊt/", pos:"v.", meaning:"查看/退房/结账——看一眼就走还是走之前结账", example:"You should check out that new restaurant." },
      { en:"suit jacket", phonetic:"/suːt ˈdʒækɪt/", pos:"n.", meaning:"西装外套——正装上身那件有型的外套", example:"He wore a dark suit jacket to the interview." },
      { en:"might", phonetic:"/maɪt/", pos:"modal v./n.", meaning:"可能/力量——不确定但有可能发生", example:"It might rain later." },
      { en:"raw", phonetic:"/rɔː/", pos:"adj.", meaning:"生的/未加工的——还没被火碰过还没被手改过", example:"I prefer raw vegetables in my salad." },
      { en:"stall", phonetic:"/stɔːl/", pos:"n./v.", meaning:"摊位/熄火——市场里的小格子间", example:"We bought fruit from a market stall." },
      { en:"blender", phonetic:"/ˈblendər/", pos:"n.", meaning:"搅拌机——把东西打碎混在一起转的机器", example:"She made a smoothie in the blender." },
      { en:"sausage", phonetic:"/ˈsɔːsɪdʒ/", pos:"n.", meaning:"香肠——肉塞进肠衣里扭成一节节", example:"We had sausages and eggs for breakfast." },
      { en:"cut up", phonetic:"/kʌt ʌp/", pos:"v.", meaning:"切碎/切块——把大的切成小块", example:"Cut up the vegetables before putting them in the soup." },
      { en:"pork", phonetic:"/pɔːrk/", pos:"n.", meaning:"猪肉——从猪身上来的肉", example:"We had roast pork for dinner." },
      { en:"crisp", phonetic:"/krɪsp/", pos:"adj./v./n.", meaning:"脆的/变脆——咬下去咔嚓一声", example:"The skin on the roast pork was perfectly crisp." },
      { en:"extreme", phonetic:"/ɪkˈstriːm/", pos:"adj./n.", meaning:"极端的/极端——推到最远的那一端", example:"The weather here is extreme in summer." },
      { en:"hairdresser", phonetic:"/ˈherdresər/", pos:"n.", meaning:"理发师——靠剪刀和梳子吃饭的人", example:"She's been going to the same hairdresser for years." },
      { en:"butcher", phonetic:"/ˈbʊtʃər/", pos:"n./v.", meaning:"屠夫/屠宰——跟肉和刀打交道的职业", example:"We buy our meat from the local butcher." },
      { en:"peanut butter", phonetic:"/ˈpiːnʌt ˈbʌtər/", pos:"n.", meaning:"花生酱——花生磨成酱涂面包的灵魂", example:"Peanut butter and jelly is a classic sandwich." },
      { en:"set up", phonetic:"/set ʌp/", pos:"v.", meaning:"建立/搭建/设置——从零开始把东西弄好", example:"They set up a stall at the market." },
      { en:"tent", phonetic:"/tent/", pos:"n.", meaning:"帐篷——布撑起来的临时小屋", example:"We pitched the tent by the river." },
      { en:"structure", phonetic:"/ˈstrʌktʃər/", pos:"n./v.", meaning:"结构/组织——东西是怎么拼在一起的", example:"The structure of this building is impressive." },
      { en:"grow", phonetic:"/ɡroʊ/", pos:"v.", meaning:"生长/增长——从小变大，从少变多", example:"Plants grow faster in spring." },
      { en:"farm", phonetic:"/fɑːrm/", pos:"n./v.", meaning:"农场/种田——在土地上养活自己的地方", example:"They live on a dairy farm." },
      { en:"shell", phonetic:"/ʃel/", pos:"n./v.", meaning:"壳/剥壳——保护里面那层硬硬的外衣", example:"We spent the afternoon shelling peas." },
      { en:"plantain", phonetic:"/ˈplæntɪn/", pos:"n.", meaning:"大蕉/车前草——长得像香蕉但要煮着吃的那种", example:"Fried plantain is a popular side dish in many countries." },
      { en:"wood pallet", phonetic:"/wʊd ˈpælɪt/", pos:"n.", meaning:"木托盘——搬运货物垫在底下的木板架", example:"The goods were stacked on wood pallets in the warehouse." },
      { en:"transport", phonetic:"/ˈtrænspɔːrt/", pos:"n./v.", meaning:"交通/运输——把人或货从这搬到那", example:"Public transport is very convenient in this city." }
    ]
  }
];
